"""
Historical Reference Baseline Data Loader.
Provides strictly read-only access to historical distributions and matrices
generated by Stage 5 Data Engineering.
"""

import json
from pathlib import Path
from typing import Dict, Any, List

BASE_DIR = Path(__file__).resolve().parent.parent.parent
DATA_ENG_PROCESSED = BASE_DIR / "data_engineering" / "processed"
DATA_ENG_REPORTS = BASE_DIR / "data_engineering" / "reports"

BASELINE_JSONL = DATA_ENG_PROCESSED / "genai_reference_baseline.jsonl"
MUTATION_FREQ_JSON = DATA_ENG_PROCESSED / "mutation_frequency.json"
MUTATION_COOC_JSON = DATA_ENG_PROCESSED / "mutation_cooccurrence.json"
BIOMARKER_DIST_JSON = DATA_ENG_PROCESSED / "biomarker_distributions.json"
RESISTANCE_DIST_JSON = DATA_ENG_PROCESSED / "treatment_resistance_distributions.json"
DATA_QUALITY_REPORT_JSON = DATA_ENG_REPORTS / "data_quality_report.json"


class ReferenceDataLoader:
    """Loads and provides structured read-only access to historical reference baselines."""

    def __init__(self):
        self.mutation_frequencies = self._load_json(MUTATION_FREQ_JSON)
        self.mutation_cooccurrences = self._load_json(MUTATION_COOC_JSON)
        self.biomarker_distributions = self._load_json(BIOMARKER_DIST_JSON)
        self.treatment_resistance = self._load_json(RESISTANCE_DIST_JSON)
        self.data_quality = self._load_json(DATA_QUALITY_REPORT_JSON)
        self.baseline_blocks = self._load_jsonl(BASELINE_JSONL)

    def _load_json(self, path: Path) -> Dict[str, Any]:
        if not path.exists():
            return {"status": "source_limitation", "reason": f"File not found: {path.name}"}
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)

    def _load_jsonl(self, path: Path) -> List[Dict[str, Any]]:
        records = []
        if not path.exists():
            return records
        with open(path, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if line:
                    records.append(json.loads(line))
        return records

    def get_gene_frequency(self, gene: str) -> float:
        """Retrieve historical cohort frequency percentage for a given gene."""
        gene_level = self.mutation_frequencies.get("gene_level_frequencies", [])
        for item in gene_level:
            if item.get("gene", "").upper() == gene.upper():
                return float(item.get("frequency_percent", 0.0))
        return 0.0

    def get_top_cooccurrences(self) -> List[Dict[str, Any]]:
        """Retrieve top historical driver co-occurrences."""
        return self.mutation_cooccurrences.get("cooccurrence_patterns", [])

    def get_resistance_alterations(self) -> List[Dict[str, Any]]:
        """Retrieve cataloged resistance alterations."""
        return self.treatment_resistance.get("documented_resistance_mechanisms", [])

    def get_summary_text(self) -> str:
        """Provide a concise summary block for prompt inclusion."""
        return (
            f"Historical Reference Baseline: N=75 NSCLC cohort harmonized from TCGA PanCancer Atlas "
            f"(WES, Stage I-IV) and MSK-IMPACT (Targeted Panel, Stage IV). "
            f"Top drivers: KRAS (24.0%), EGFR (22.7%), TP53 (17.3%). "
            f"TMB median: 7.0 mut/Mb; PD-L1 TPS: 60% Low (1-49%), 28% High (>=50%)."
        )
